name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: config
      run: sudo gem install ldid 
    - name: make
      run: make all
    #- name: make check
    #  run: make check
   # - name: make distcheckmake distcheck
