name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: config
      run: brew install ldid 
    - name: make
      run: make all
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: RamDisk 
        path: ramdisk.dmg
        retention-days: 5
    #- name: make check
    #  run: make check
   # - name: make distcheckmake distcheck
